baseURL = 'https://bhankas.org/'
languageCode = 'en-us'
title = 'bhankas'
copyright = "anon"

# Theme config : Bear Cub
theme = 'hugo-bearcub'
defaultContentLanguage = 'en'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[menu]

[[menu.main]]
  name = "blog"
  pageRef = "/blog"
  weight = 1

[[menu.main]]
  name = "braindump"
  pageRef = "/braindump"
  weight = 2

[[menu.main]]
  name = "reading"
  pageRef = "/reading"
  weight = 3

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    title = "bhankas"
    languageName = "en-US ????"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      blogPath = "/blog" # Path to your blog section (used by RSS)
      madeWith = "https://www.gnu.org/software/emacs/"
      license = "(CC BY 4.0)"

[params]
  # The description of your website
  description = "ramblings of an adhd-riddled soul"

  # The path to your favicon
  # favicon = "images/favicon.png"

  # This title is used as the site_name on the Hugo's internal opengraph
  # structured data template
  title = "bhankas"

  # Dates are displayed following the format below. For more information about
  # formatting, see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # If your blog is multilingual but you haven't translated a page, this theme
  # will create a disabled link. By setting `hideUntranslated` to true, you can
  # have the theme simply not show any link
  hideUntranslated = true

  # (EXPERIMENTAL) This theme is capable of dynamically generating social cards
  # for posts that don't have `images` defined in their front matter; By setting
  # `generateSocialCard` to false, you can prevent this behavior. For more
  # information see layouts/partials/seo_tags.html
  generateSocialCard = false
