:PROPERTIES:
:ID:       20230402T092853.552049
:END:
#+title: In praise of Nix(OS) [DRAFT]
#+slug: in_prais_of_nix_os
#+date: <2023-04-01 Sat>
#+filetags: 

* Why

In late 2019, I had been using Ubuntu for nearly a year.

I chose Ubuntu because I had a new laptop with nVidia GPU, didn't want to mess with drivers, and had read Ubuntu had the best support for the same.
It was correct. But 'best' does not mean perfect. I had to use a non-LTS version because the hardware was new and I needed newer kernel, the usual story.

But, here came the twist. By May that year, my version of Ubuntu was off upstream support. I couldn't upgrade because my dissertation depended on machine being available, and Ubuntu upgrade was the last thing I trusted. For nearly half year, I was stuck on unsupported, very likely security-devoid software.

And so I took a vow that will not be the case as soon as I was done with my Master's.

* Romance begins

Boy oh boy was it a rough ride.. I cannot understate just how bad the beginning of NixOS adventure for me was. It took me more than a day to just get the boot shit right (If it isn't clear yet, I was and still largely am, a n00b).

Then, I had to get my applications and everything else in order, and by hook+crook+lot-of-copy-pasting+trial-and-error later, about a week in, I was set.

* Falling in love

Couple years in, I started grokking the benefits.
- For first time in my life, my machine remained unformatted for more than a year.

  This was huge! I had just started my first job and didn't have as much time as before, and this kind of thing was a pretty significant life upgrade.

- I never not had my machine.

  Ubuntu had already given me black screen after update, and that had scarred me for life. That never happened here, and this is where I started falling for NixOS.

* All the benefits
1. Never not have your machine available
   With NixOS, your machine is never broken beyond a reboot. Upgrades don't finish if a package is broken. Config (where abstracted) doesn't build if upstream breaks it in an update. Updates are atomic and NEVER get stuck halfway. And even after all this something still breaks (its possible, especially for intrpid users like yours truly), a simple reboot into previous generation via boot menu is all it takes to get a fix.

   Never worrying about system breakage is a yuuuge relief for mind.

2. Learn once, forget forever
